# Generated by Django 4.0.5 on 2022-07-07 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='derscription',
            field=models.CharField(default='default', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
            preserve_default=False,
        ),
    ]
