# Generated by Django 4.0.5 on 2022-07-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_milestone_derscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='derscription',
            new_name='description',
        ),
    ]
