# Generated by Django 4.0.5 on 2022-07-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_last_worked_on_project_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_worked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
