# Generated by Django 4.0.5 on 2022-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_last_worked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
