# Generated by Django 4.0.5 on 2022-07-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
