# Generated by Django 4.0.5 on 2022-07-10 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_session_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='default', max_length=120, validators=[django.core.validators.MaxLengthValidator(120)]),
            preserve_default=False,
        ),
    ]
